### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by emahuni** [danilosampaio/semantic-kanban#12]
I have git cloned and ran `npm run dev`. The example runs but i can't make any changes such as adding new cards, deleting old ones, adding new team members, tasks or anything else, or editing existing cards and any texts. It's as if the whole app is readonly. Am I missing something?

**Comment by danilosampaio** [comment]
Hi @emahuni 
The example is incomplete, the update method only prints in console:
https://github.com/danilosampaio/semantic-kanban/blob/22c3fa333e5bc989025a0472c9961cad0e7230c0/src/App.vue#L78

Thanks for your feedback, i'm going to fix it.

**Comment by danilosampaio** [comment]
Fixed in version `1.4.3`
